remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: CodeGraph MCP Server for Java Projects
description: A Java-based multi-module project that uses ClassGraph to scan JARs (and IntelliJ PSI), persists the resulting class-dependency graph in an embedded Neo4j database, and exposes it over the MCP protocol via both a CLI folder-watcher and an IntelliJ plugin.
show_downloads: true
