name: Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Generate Gradle Wrapper
        run: gradle wrapper --gradle-version 8.5 --distribution-type all --console=plain
      - name: Build Project
        run: ./gradlew build :intellij:buildPlugin --no-daemon --console=plain
