name: Release

on:
  release:
    types: [published, created]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Generate Gradle Wrapper
        run: gradle wrapper --gradle-version 8.5 --distribution-type all --console=plain
      - name: Build Artifacts
        run: ./gradlew :cli:shadowJar :intellij:buildPlugin --no-daemon --console=plain
      - name: Detect Tag
        id: tag
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            echo "tag_name=${{ github.ref_name }}" >> "$GITHUB_OUTPUT"
          else
            echo "tag_name=${{ github.event.release.tag_name }}" >> "$GITHUB_OUTPUT"
          fi
      - name: Pre-release Check
        id: pre
        run: |
          TAG="${{ steps.tag.outputs.tag_name }}"
          if [[ "$TAG" == *-* ]]; then
            echo "is_prerelease=true" >> "$GITHUB_OUTPUT"
          else
            echo "is_prerelease=false" >> "$GITHUB_OUTPUT"
          fi
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.tag_name }}
          name: ${{ steps.tag.outputs.tag_name }}
          prerelease: ${{ steps.pre.outputs.is_prerelease }}
          generate_release_notes: true
          files: |
            cli/build/libs/cli-all.jar
            intellij/build/distributions/*.zip
          draft: false
